
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author win7
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    public ADMIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deks = new javax.swing.JDesktopPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableadmin = new javax.swing.JTable();
        btnhome1 = new javax.swing.JButton();
        btntambah3 = new javax.swing.JButton();
        btntampildata1 = new javax.swing.JButton();
        txtharga = new javax.swing.JTextField();
        txtnamakapal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtfasilitas = new javax.swing.JTextField();
        txtnamakapten = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtjamjln = new javax.swing.JTextField();
        btntujuan = new javax.swing.JComboBox<>();
        txtnmrkapal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btntambah1 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        bobotkpl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deks.setPreferredSize(new java.awt.Dimension(1268, 709));

        tableadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableadmin.setInheritsPopupMenu(true);
        tableadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableadminMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableadmin);

        btnhome1.setBackground(new java.awt.Color(0, 255, 255));
        btnhome1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhome1.setText("HOME");
        btnhome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome1ActionPerformed(evt);
            }
        });

        btntambah3.setBackground(new java.awt.Color(255, 102, 51));
        btntambah3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntambah3.setText("TAMBAH 2");
        btntambah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambah3ActionPerformed(evt);
            }
        });

        btntampildata1.setBackground(new java.awt.Color(0, 255, 204));
        btntampildata1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntampildata1.setText("TAMPIL");
        btntampildata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampildata1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nama Kapten");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Fasilitas");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Kapal");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Harga");

        btntujuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRIP 3D2N", "=Pulau Komodo", "=Pink Beach+Snorkling", "=Taka Makasar", "=Pulau Padar+Snorkling", "=Pulau Kelor", "TRIP 4D3N", "=Pulau Rinca", "=Pulau Komodo", "=Pulau Kelor", "=Pulau Padar+Snorkling", "=Pink Beach+Snorkling", "=Pulau Kalong", "TRIP 5D4N", "=Pulau Rinca", "=Pulau Padar+snorkling", "=Pulau Kalong", "=Pink Beach+Snorkling", "=Pulau Kalong" }));
        btntujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntujuanActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Keterangan");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tujuan");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nomor Kapal");

        btntambah1.setBackground(new java.awt.Color(0, 0, 255));
        btntambah1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntambah1.setText("TAMBAH 1");
        btntambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambah1ActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(102, 255, 51));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOBOT KAPAL");

        deks.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(btnhome1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(btntambah3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(btntampildata1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(txtharga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(txtnamakapal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(txtfasilitas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(txtnamakapten, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(txtjamjln, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(btntujuan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(txtnmrkapal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(btntambah1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(btnupdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(bobotkpl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deks.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deksLayout = new javax.swing.GroupLayout(deks);
        deks.setLayout(deksLayout);
        deksLayout.setHorizontalGroup(
            deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deksLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deksLayout.createSequentialGroup()
                        .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deksLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(30, 30, 30)
                                .addComponent(txtjamjln, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btntampildata1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(deksLayout.createSequentialGroup()
                                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtnmrkapal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(btntujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamakapal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel14))
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17))))
                            .addGroup(deksLayout.createSequentialGroup()
                                .addComponent(btntambah3)
                                .addGap(32, 32, 32)))
                        .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(deksLayout.createSequentialGroup()
                                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addComponent(btntambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnhome1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addComponent(txtnamakapten, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(deksLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(bobotkpl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        deksLayout.setVerticalGroup(
            deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deksLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamakapal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtnamakapten, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtnmrkapal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(bobotkpl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deksLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)))
                    .addGroup(deksLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addGroup(deksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjamjln, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(btntampildata1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhome1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 455, Short.MAX_VALUE))
        );

        jMenu2.setText("TABLE DATA PEMESANAN");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("D:\\pemrograman\\Logopit_1575611788743.png")); // NOI18N
        jMenuItem1.setText("Table");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deks, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deks, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        tablepesanan admin = new tablepesanan();
        deks.add(admin);
        admin.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tableadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableadminMouseClicked
        // TODO add your handling code here:
        int baris= tableadmin.rowAtPoint(evt.getPoint());
        if(baris>-1){

            txtnmrkapal.setText( tableadmin.getValueAt(baris, 0).toString());

            txtnamakapal.setText(tableadmin.getValueAt(baris, 1).toString());

            txtnamakapten.setText( tableadmin.getValueAt(baris, 2).toString());

            btntujuan.setSelectedItem( tableadmin.getValueAt(baris, 3).toString());

            txtharga.setText(tableadmin.getValueAt(baris, 4).toString());

            txtfasilitas.setText(tableadmin.getValueAt(baris, 5).toString());
            
             bobotkpl.setText(tableadmin.getValueAt(baris, 6).toString());

            txtjamjln.setText(tableadmin.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tableadminMouseClicked

    private void btntujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntujuanActionPerformed

    private void btntambah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambah3ActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "INSERT INTO goship3 VALUE ('" + txtnmrkapal.getText()+"' , '" + txtnamakapal.getText()+"' , '" + txtnamakapten.getText()+"' , '" +btntujuan.getSelectedItem()+"' , '" + txtharga.getText()+"' , '" + txtfasilitas.getText()+"','"+
                    bobotkpl.getText()+"', '" +txtjamjln.getText()+" , "+ "')";
            java.sql.Connection con = (Connection)koneksidb.configDB();
            java.sql.PreparedStatement pr= con.prepareStatement(sql);
            //  ResultSet rs = st.executeQuery(sql);

            pr.execute();
          JOptionPane.showMessageDialog(null, "Tambah data goship3 sukses.");
           DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Nomor Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Nama Kapten");
        model.addColumn("Tujuan");
        model.addColumn("Harga");
        model.addColumn("Fasilitas");
        model.addColumn("BoBot Kapal");
        model.addColumn("Keterangan");

        try{

          sql = "select * from goship3";

            java.sql.Connection conn = (com.mysql.jdbc.Connection)koneksidb.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});

            }

            tableadmin.setModel(model);

        }catch(SQLException e){
            System.out.println("error" + e.getMessage());

        }

        } catch(HeadlessException | SQLException e){
            System.out.println("error"+e.getMessage());
        }
    }//GEN-LAST:event_btntambah3ActionPerformed

    private void btntampildata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampildata1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Nomor Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Nama Kapten");
        model.addColumn("Tujuan");
        model.addColumn("Harga");
        model.addColumn("Fasilitas");
        model.addColumn("BoBot Kapal");
        model.addColumn("Keterangan");

        try{

         String sql = "select * from goship3";

            java.sql.Connection conn = (com.mysql.jdbc.Connection)koneksidb.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),
                    res.getString(7),res.getString(8)});

            }

            tableadmin.setModel(model);

        }catch(SQLException e){
            System.out.println("error" + e.getMessage());

        }
       
    }//GEN-LAST:event_btntampildata1ActionPerformed

    private void btnhome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome1ActionPerformed
        // TODO add your handling code here:
        Beranda n = new Beranda();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnhome1ActionPerformed

    private void btntambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambah1ActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "INSERT INTO goship VALUE ('" + txtnmrkapal.getText()+"' , '" + txtnamakapal.getText()+"' , '" + txtnamakapten.getText()+"' , '" +btntujuan.getSelectedItem()+"' , '" + txtharga.getText()+"' , '" + txtfasilitas.getText()+"', '" +bobotkpl.getText()+"','"+txtjamjln.getText()+" , "+ "')";
            java.sql.Connection conn = (Connection)koneksidb.configDB();
            java.sql.PreparedStatement p= conn.prepareStatement(sql);
            //  ResultSet rs = st.executeQuery(sql);

            p.execute();
            JOptionPane.showMessageDialog(null, "Tambah data goship sukses.");

        } catch(HeadlessException | SQLException e){
            System.out.println("error"+e.getMessage());
        }
    }//GEN-LAST:event_btntambah1ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
         try {

            String sql = "UPDATE goship3 SET nmr_kapal = '" + txtnmrkapal.getText()+"' ,nama_kapal= '" + txtnamakapal.getText()+"' ,nama_kapten= '" + txtnamakapten.getText()+"',tujuan='" +btntujuan.getSelectedItem()+"' ,harga='" + txtharga.getText()+"',fasilitas='" + txtfasilitas.getText()+"',BoBot='"+bobotkpl.getText()+"' ,keterangan='" +txtjamjln.getText()+
                    "'Where nmr_kapal= '"+txtnmrkapal.getText()+"'";
            java.sql.Connection conn = (Connection)koneksidb.configDB();
            java.sql.PreparedStatement p= conn.prepareStatement(sql);
            //  ResultSet rs = st.executeQuery(sql);

            p.execute();
            JOptionPane.showMessageDialog(null, "UPDATE SUKSES");
             DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Nomor Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Nama Kapten");
        model.addColumn("Tujuan");
        model.addColumn("Harga");
        model.addColumn("Fasilitas");
        model.addColumn("BoBot Kapal");
        model.addColumn("Keterangan");

        try{

            sql = "select * from goship3";

            java.sql.Connection con = (com.mysql.jdbc.Connection)koneksidb.configDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});

            }

            tableadmin.setModel(model);

        }catch(SQLException e){
            System.out.println("error" + e.getMessage());

        }

        } catch(HeadlessException | SQLException e){
            System.out.println("error"+e.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bobotkpl;
    private javax.swing.JButton btnhome1;
    private javax.swing.JButton btntambah1;
    private javax.swing.JButton btntambah3;
    private javax.swing.JButton btntampildata1;
    private javax.swing.JComboBox<String> btntujuan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JDesktopPane deks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableadmin;
    private javax.swing.JTextField txtfasilitas;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjamjln;
    private javax.swing.JTextField txtnamakapal;
    private javax.swing.JTextField txtnamakapten;
    private javax.swing.JTextField txtnmrkapal;
    // End of variables declaration//GEN-END:variables
}
